import type { PublicKeyCredentialCreationOptionsJSON } from '@simplewebauthn/typescript-types';
import type { UserRelation } from '../../interface';

/**
 * The DTO sent from the backend to the frontend after registering a user with WebAuthn.
 */
export class BaseUserRelationAndOptionsDto {
  /**
   * The user that was just created.
   */
  userRelation!: UserRelation;

  /**
   * The public key credential creation options generated by the backend for the frontend to use.
   */
  options!: PublicKeyCredentialCreationOptionsJSON;
}
