import type { PublicKeyCredentialCreationOptionsJSON } from '@simplewebauthn/typescript-types';
import type { UserRelation } from '../../interface';

/**
 * The DTO sent from the backend to the frontend after registering a user with WebAuthn.
 */
export class UserRelationAndOptionsDto {
  /**
   * @param userRelation The user and its related entities.
   * @param options The public key credential creation options generated by the backend for the frontend to use.
   */
  constructor(
    readonly userRelation: UserRelation,
    readonly options: PublicKeyCredentialCreationOptionsJSON,
  ) {}
}
