import type { AuthenticationResponseJSON } from '@simplewebauthn/typescript-types';
import { IsDefined } from 'class-validator';
import { responseIsDefined } from '../../constant';
import { EmailDto } from './email.dto';

/**
 * The DTO sent from the frontend to the backend to submit the authenticator's response after feeding the backend's authentication options to it.
 * Suitable for use with POST requests.
 */
export class WebAuthnLoginDto extends EmailDto {
  /**
   * The credential generated by the frontend's authenticator using the backend's authentication options.
   */
  @IsDefined({ message: responseIsDefined })
  readonly response: AuthenticationResponseJSON;

  constructor(email: string, response: AuthenticationResponseJSON) {
    super(email);
    this.response = response;
  }
}
