import type { AuthenticationCredentialJSON } from '@simplewebauthn/typescript-types';
import { BaseEmailDto } from './base-email.dto';

/**
 * The DTO sent from the frontend to the backend to submit the authenticator's response after feeding the backend's authentication options to it.
 * Suitable for use with POST requests.
 */
export class BaseWebAuthnLoginDto extends BaseEmailDto {
  /**
   * The credential generated by the frontend's authenticator using the backend's authentication options.
   */
  credential!: AuthenticationCredentialJSON;
}
