import { User } from '@newbee/shared/util';
import type { PublicKeyCredentialCreationOptionsJSON } from '@simplewebauthn/typescript-types';

/**
 * The DTO sent from the backend to the frontend after registering a user with WebAuthn.
 */
export class BaseUserAndOptionsDto {
  /**
   * The user that was just created.
   */
  user!: User;

  /**
   * The public key credential creation options generated by the backend for the frontend to use.
   */
  options!: PublicKeyCredentialCreationOptionsJSON;
}
