import type { PublicKeyCredentialCreationOptionsJSON } from '@simplewebauthn/typescript-types';
import { BaseLoginDto } from './base-login.dto';

/**
 * The DTO sent from the backend to the frontend after registering a user with WebAuthn.
 */
export class BaseUserCreatedDto extends BaseLoginDto {
  /**
   * The public key credential creation options generated by the backend for the frontend to use.
   */
  options!: PublicKeyCredentialCreationOptionsJSON;
}
