import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import {
  authenticator,
  authenticatorVersion,
  BaseRegistrationResponseDto,
  options,
} from '@newbee/shared/data-access';
import { Authenticator } from '@newbee/shared/util';
import { startRegistration } from '@simplewebauthn/browser';
import type { PublicKeyCredentialCreationOptionsJSON } from '@simplewebauthn/typescript-types';
import { from, Observable, switchMap } from 'rxjs';

/**
 * The service tied to the API's authenticator endpoints.
 * Specifically handles registering new authenticators for already logged in users.
 */
@Injectable({ providedIn: 'root' })
export class AuthenticatorService {
  constructor(private readonly http: HttpClient) {}

  /**
   * Sends a POST request to make the backend generate public key creation options.
   * @returns An observable of the backend's public key creation options.
   */
  createOptions(): Observable<PublicKeyCredentialCreationOptionsJSON> {
    return this.http.post<PublicKeyCredentialCreationOptionsJSON>(
      `/api/v${authenticatorVersion}/${authenticator}/${options}`,
      {}
    );
  }

  /**
   * Sends a POST request to save the new authenticator.
   *
   * @param options The public key creation options generated by the backend.
   * @returns An observable of the newly created authenticator.
   */
  create(
    options: PublicKeyCredentialCreationOptionsJSON
  ): Observable<Authenticator> {
    return from(startRegistration(options)).pipe(
      switchMap((response) => {
        const registrationResponseDto: BaseRegistrationResponseDto = {
          response,
        };
        return this.http.post<Authenticator>(
          `/api/v${authenticatorVersion}/${authenticator}`,
          registrationResponseDto
        );
      })
    );
  }
}
