import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { apiVersion } from '@newbee/shared/data-access';
import {
  Authenticator,
  Keyword,
  NameDto,
  RegistrationResponseDto,
} from '@newbee/shared/util';
import { startRegistration } from '@simplewebauthn/browser';
import type { PublicKeyCredentialCreationOptionsJSON } from '@simplewebauthn/typescript-types';
import { Observable, from, switchMap } from 'rxjs';

/**
 * The service tied to the API's authenticator endpoints.
 * Specifically handles registering new authenticators for already logged in users.
 */
@Injectable({ providedIn: 'root' })
export class AuthenticatorService {
  /**
   * The base API URL for dealing with authenticators.
   */
  static baseApiUrl = `/${Keyword.Api}/v${apiVersion.authenticator}/${Keyword.Authenticator}`;

  constructor(private readonly http: HttpClient) {}

  /**
   * Sends a GET request to get all of the authenticators of the logged in user.
   * @returns An observable containing all of the logged in user's authenticators.
   */
  getAuthenticators(): Observable<Authenticator[]> {
    return this.http.get<Authenticator[]>(AuthenticatorService.baseApiUrl);
  }

  /**
   * Sends a POST request to make the backend generate public key creation options.
   * @returns An observable of the backend's public key creation options.
   */
  createOptions(): Observable<PublicKeyCredentialCreationOptionsJSON> {
    return this.http.post<PublicKeyCredentialCreationOptionsJSON>(
      `${AuthenticatorService.baseApiUrl}/${Keyword.Options}`,
      {},
    );
  }

  /**
   * Sends a POST request to save the new authenticator.
   *
   * @param options The public key creation options generated by the backend.
   * @returns An observable of the newly created authenticator.
   */
  create(
    options: PublicKeyCredentialCreationOptionsJSON,
  ): Observable<Authenticator> {
    return from(startRegistration(options)).pipe(
      switchMap((response) => {
        const registrationResponseDto = new RegistrationResponseDto(response);
        return this.http.post<Authenticator>(
          AuthenticatorService.baseApiUrl,
          registrationResponseDto,
        );
      }),
    );
  }

  /**
   * Sends a PATCH request to edit the name of an authenticator.
   *
   * @param id The ID of the authenticator to edit.
   * @param name The new name for the authenticator.
   *
   * @returns An observable of the updated authenticator.
   */
  editName(id: string, name: string | null): Observable<Authenticator> {
    const nameDto = new NameDto(name);
    return this.http.patch<Authenticator>(
      `${AuthenticatorService.baseApiUrl}/${id}`,
      nameDto,
    );
  }

  /**
   * Sends a DELETE request to delete the given authenticator by ID.
   *
   * @param id The ID of the authenticator to delete.
   * @returns A null observable.
   */
  delete(id: string): Observable<null> {
    return this.http.delete<null>(`${AuthenticatorService.baseApiUrl}/${id}`);
  }
}
